"""SQLite-backed asset, scene, and artifact catalog."""

from uefactory.catalog.database import (
    ASSET_STATUSES,
    LICENSE_TIERS,
    SCENE_BUILD_ARTIFACT_KINDS,
    SCENE_RENDER_ARTIFACT_KINDS,
    SCENE_STATUSES,
    SCHEMA_VERSION,
    SUPPORTED_LICENSES,
    ArtifactRecord,
    ArtifactUpsert,
    AssetRecord,
    AssetUpsert,
    Catalog,
    CatalogConflictError,
    CatalogError,
    CatalogSchemaError,
    CatalogStats,
    CatalogValidationError,
    SceneArtifactRecord,
    SceneArtifactUpsert,
    SceneObjectRecord,
    SceneObjectUpsert,
    SceneRecord,
    SceneUpsert,
)

__all__ = [
    "ASSET_STATUSES",
    "LICENSE_TIERS",
    "SCHEMA_VERSION",
    "SCENE_BUILD_ARTIFACT_KINDS",
    "SCENE_RENDER_ARTIFACT_KINDS",
    "SCENE_STATUSES",
    "SUPPORTED_LICENSES",
    "ArtifactRecord",
    "ArtifactUpsert",
    "AssetRecord",
    "AssetUpsert",
    "Catalog",
    "CatalogConflictError",
    "CatalogError",
    "CatalogSchemaError",
    "CatalogStats",
    "CatalogValidationError",
    "SceneArtifactRecord",
    "SceneArtifactUpsert",
    "SceneObjectRecord",
    "SceneObjectUpsert",
    "SceneRecord",
    "SceneUpsert",
]
